### ISSUE TITLE
[BUG REPORT]: NAEFS Precipitation Product Incorrect Precipitation Totals

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/cumulus#232]
## Describe the bug

The NAEFS Precipitation Product is showing over 70 inches of rain in some areas. Thinking there is either a unit error (mm vs. inches) or incorrect band being processed.

## Steps To Reproduce

> Based on user report. Development team needs to reproduce. Add More Detail Here.

## Expected behavior

Precipitation totals for NAEFS Precipitation Product are reasonable compared to on-the-ground measurements.

## Actual behavior

Precipitation totals around St. Louis, MO > 70 inches, which is not reasonable.

## Additional context

Need to implement testing procedures to try to catch this in the future.

**Comment by jeffsuperglide** [comment]
Reference https://github.com/USACE/cumulus-api/tree/bugfix/naefs-qpf-qtf

NAEFS QPF and QTF products are processed within the same geo-processor.  A Python dictionary object defines the netCDF variables `QPF` and `QTF`.  Resulting Tiff file names were not defined uniquely enough to keep files from being overwritten.  The netCDF variable name is now used within the generated file name.  This solves the issue where all products resulted in `QTF`.

Apparently, C and Fortran handle data arrays opposite.  The NAEFS geo-processor uses `numpy.flipud()` to flip the array (u)p (d)own.  Doing so puts the Tiff data like that of a `grib --> Tiff`.  Reference https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg03585.html for C and Fortran difference in arrays.

> The C programming language has the outermost dimension in the leftmost position and the innermost dimension in the rightmost position.

> The Fortran programming language has the outermost dimension in the
rightmost position and the innermost dimension in the leftmost position.

**Comment by brettpalmberg** [comment]
Thank you @jeffsuperglide.

@adamscarberry, can you help with deleting the current archive of NAEFS files from the Cumulus database and S3 object store for the following products?
* cumulus/products/naefs-mean-**qpf**-06h/
* cumulus/products/naefs-mean-**qtf**-06h/

**Comment by brettpalmberg** [comment]
Steps to Resolve :

# Develop Environment

- [ ] Merge USACE/cumulus-api#320 (Bug fix into develop environment)
- [ ] Develop; Delete database records for products referenced in comment above
- [ ] Develop; Delete corresponding S3 Files
- [ ] Develop; Resend recent NAEFS files for re-processing using LDM
- [ ] Develop; Observe processing in Grafana
- [ ] Develop; Validate results from test download of DSSv7 format, conversion to DSSv6.

# Stable Environment

- [ ] Merge `develop` --> `stable` (Merge Commit)
- [ ] Stable; Delete database records for products referenced in comment above
- [ ] Stable; Delete corresponding S3 Files
- [ ] Stable; Resend recent NAEFS files for re-processing using LDM
- [ ] Stable; Observe processing in Grafana
- [ ] Stable; Validate results from test download of DSSv7 format, conversion to DSSv6.

**Comment by adamscarberry** [comment]
Packager is setting stats min value to -1 when converting to DSS v6.  @jeffsuperglide is working the issue.

**Comment by brettpalmberg** [comment]
@adamscarberry, it looks like the database records for NAEFS and corresponding S3 files have been deleted per the checklist. I just checked them off the list.  Feel free to reverse the checkmark if I'm incorrect.

**Comment by brettpalmberg** [comment]
> Develop; Validate results from test download of DSSv7 format, conversion to DSSv6.

Initial validation showed additional work required in `async_packager` for DSS file downloads. Thanks @jeffsuperglide for taking care of this in USACE/cumulus#321 which has been merged now.

**Comment by jeffsuperglide** [comment]
> Develop; Validate results from test download of DSSv7 format, conversion to DSSv6.

NAEFS QPF and QTF request made from develop-cumulus.corps.cloud.  DSS7 grid records randomly selected to plot and tabulate; all looks good.  Converted to DSS6, random record selection, plotted and tabulated.  Plots and statistics look good.

Thanks to @ktarbet and guidance on the DSS statistics updates.

**Comment by brettpalmberg** [comment]
>  Plots and statistics look good.

Awesome! I just ✅ the last box in the dev implementation.  Are we ready to update `stable`?

**Comment by brettpalmberg** [comment]
>  Merge develop --> stable (Merge Commit)

Done. ✅

**Comment by jeffsuperglide** [comment]
> Stable; Validate results from test download of DSSv7 format, conversion to DSSv6.

Made requests for NAEFS QPF and QTF on stable.  Plotted and tabulated DSS7 records, converted to DSS6, plotted and tabulated DSS6 records and all looks good.  Also, requested MRMS Pass1 and look good.

**Comment by brettpalmberg** [comment]
👍🏻 Awesome. Thanks @jeffsuperglide, @adamscarberry. If everything still looks good on Monday, let's close this issue.

**Comment by jeffsuperglide** [comment]
Made NAEFS download request both from web app and CAVI script.  Looks good.  Additional request made for MRMS through the CAVI script and both NAEFS and MRMS show in the CAVI Visualization tab.  Grids downloaded from Cumulus and converted to DSS6 using the CAVI script now render in the CAVI Visualization tab with `tiffdss` in the `packager`.  DSS6 grids in the CAVI Visualization tab did not render with `pydsstools` in the packager.

**Comment by adamscarberry** [comment]
> the CAVI script now render in the CAVI Visualization tab with tiffdss

@jeffsuperglide What's the trick to showing grids in CAVI (I'm using 3.2.3)?  I still get nothing.

![image](https://user-images.githubusercontent.com/46494851/179608805-82aaefbb-785c-4ce0-9030-d8fd0316b1f3.png)

**Comment by jeffsuperglide** [comment]
@adamscarberry - Any feedback on NAEFS corrections?

**Comment by brettpalmberg** [comment]
@adamscarberry, @jeffsuperglide, I re-raised the request (email) to confirm everything looks good from the end-user perspective.

**Comment by adamscarberry** [comment]
Russ confirmed grids were good.

**Comment by brettpalmberg** [comment]
Awesome!  Thanks for closing @adamscarberry.
